#!/usr/bin/env bash

# GPG Mail
# sign new email
defaults write org.gpgtools.gpgmail SignNewEmailsByDefault -int 1
# change default method to `s/mime`
defaults write org.gpgtools.gpgmail DefaultSecurityMethod -int 2
